### ISSUE TITLE
"requireCordovaModule" to load non-cordova module 

### ISSUE THREAD

**Issue by pecet86** [blakgeek/cordova-plugin-app-name#16]
Hello
cordova 9.0.0
cordova-android 8.0.0

Using "requireCordovaModule" to load non-cordova module "semver" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by Scombr0** [comment]
Try my PR #15 until it gets merged here.

**Comment by ghost** [comment]
Same problem here

**Comment by blakgeek** [comment]
Fixed in version 1.0.7
